"""Fixed-parameter walk-forward validation contract and offline tooling."""

from trading_bot_lab.walk_forward.contract import (
    CONTRACT_DIRECTORY,
    FOLD_IDS,
    FOLDS,
    OBSERVATION_PREFIX,
    PROJECT_DIRECTORY,
    PROTOCOL_NAME,
    PROTOCOL_VERSION,
    SCHEMA_VERSION,
    Fold,
    ProtocolBundle,
    WalkForwardContractError,
    load_protocol_bundle,
)
from trading_bot_lab.walk_forward.observation import (
    WalkForwardObservationError,
    aggregate_observation_files,
    aggregate_observations,
    extract_observation,
    load_aggregate_record,
    load_observation,
    normalize_aggregate_record,
    normalize_observation,
    parse_observation_log,
    write_aggregate_files,
    write_aggregate_record,
)
from trading_bot_lab.walk_forward.operator import (
    CloudBacktestCommand,
    WalkForwardOperatorError,
    build_cloud_command_plan,
    phase_is_read_only,
)

__all__ = [
    "CONTRACT_DIRECTORY",
    "FOLDS",
    "FOLD_IDS",
    "OBSERVATION_PREFIX",
    "PROJECT_DIRECTORY",
    "PROTOCOL_NAME",
    "PROTOCOL_VERSION",
    "SCHEMA_VERSION",
    "CloudBacktestCommand",
    "Fold",
    "ProtocolBundle",
    "WalkForwardContractError",
    "WalkForwardObservationError",
    "WalkForwardOperatorError",
    "aggregate_observation_files",
    "aggregate_observations",
    "build_cloud_command_plan",
    "extract_observation",
    "load_aggregate_record",
    "load_observation",
    "load_protocol_bundle",
    "normalize_aggregate_record",
    "normalize_observation",
    "parse_observation_log",
    "phase_is_read_only",
    "write_aggregate_files",
    "write_aggregate_record",
]
